### PR TITLE
refactor: style

### LINKED ISSUE #120: [P?] Reformat code style
Previous code style was not working for some reason from IntelliJ.

```
IntelliJ IDEA code style XML import failed with error message: Can't load code style scheme true.
```

### PR DESCRIPTION
**Pull request by seiwonpark**
Re-configured style config. Now, this will work with no problem.

This closes #120

### CODE REVIEW

**Comment by seiwonpark** [comment]
Q. @kimjinmyeong  // Was there any problem running `SurveyControllerTest`? This first didn't work but it passed afterwards.

### Initial Try (right away from cloning this repository)
Screenshot 2023-04-25 at 10 48 49 PM

<br/>   

### Second Try
Screenshot 2023-04-25 at 10 49 28 PM

**Comment by bezzang-dev** [comment]
image

I have also experienced a similar situation where using `LocalDateTime.now()` to create a test object caused issues. Therefore, it seems like we should set the time manually instead of using `LocalDateTime.now()`.

**Comment by seiwonpark** [comment]
> image
> 
> I have also experienced a similar situation where using `LocalDateTime.now()` to create a test object caused issues. Therefore, it seems like we should set the time manually instead of using `LocalDateTime.now()`.

Which test was this? On every test that uses `LocalDateTime.now()`?

**Comment by bezzang-dev** [comment]
It seems that the issue only occurs in the `SurveyControllerTest` -> `testUpdateSurvey`.

**Review by bezzang-dev — APPROVED** [review]
LGTM! Thanks!

**Comment by seiwonpark** [comment]
This is weird. Let me check a little bit

**Pull request merged**
