### PR TITLE
chore: added logo assets

### PR DESCRIPTION
**Pull request by seiwonpark**
Added logo assets.
- favicon
- logo (Full title)

Used `.webp` to optimize file.

### CODE REVIEW

**Review by sanghyun1128 — APPROVED** [review]
LGTM!

**Comment by ohsung1125** [comment]
LGTM!

**Comment by seiwonpark** [comment]
@ohsung1125 If you approve this PR, please `review` this PR.

It can be done by `Files Changed` > `Review` > `Approve with Comment`

**Review by ohsung1125 — APPROVED** [review]
LGTM!

**Pull request merged**
