### PR TITLE
feat: development database and package setup

### PR DESCRIPTION
**Pull request by seiwonpark**
Modified `application.properties` to `application.yml` for readability and later complex configuration. And we need to uniform our configuration files but if considering aws, we'd better use `.yml`.

Also database is set for dev.

You can set up database on your mac with following script

https://gist.github.com/SeiwonPark/857e7fd0015b4e841cdb56ad2da54161 (**Modified**)
(If there's an error, please send me a DM)

### CODE REVIEW

**Comment by seiwonpark** [comment]
Installing database directly on the machine is not a good idea and we have another option: dockerizing our application. So let's use postgresql on local for some test for the moment. But also there could be another good question: `WHY DO WE NEED DOCKERIZATION?` can you answer it?

**Comment by bezzang-dev** [comment]
I've never used a docker, so I studied and thought about the question *`WHY DO WE NEED DOCKERIZATION?`*

When we use docker, we define things about the development and the execution environment. Sharing created images can have the effect of running applications in the same development environment, even if the actual development environment is different between users.

This reduces the burden on developers to care about their development and execution environments. It is also convenient for migration to AWS services.

I still have to study more, but I think it's a good way to dockerize our application.

Then, Do you mean to install database directly on the machine for now, and dockerizing it later?

**Comment by seiwonpark** [comment]
@kimjinmyeong (Sorry my comment was misleading. Let's use **postgresql on local machine not on docker**) Yes just for local development. Dockerizing gives us huge advantages like what you've mentioned. But during the development process, it's quite tough to manage logs from containers. Though we can check them via log files or follow option(`docker logs --follow <container ID>`) for real time logging, logs will be removed when containers are deleted. So need to mount volumes to keep logs to make them visible from host machine. 

Well, it's quite hard to choose. Dockerizing? Good! Managing containers in pods with auto-scaling/healing! Yes good! But what we also need to consider is whether it's efficient for our situation for now. 

So, I'm suggesting we use postgres on our machines only for local/test environment (we face some issues of course) and then dockerize all servers for production?

**Comment by seiwonpark** [comment]
@kimjinmyeong  ah, please also check [https://github.com/mooyoul/poo.email/issues/1#issuecomment-1381077954](https://github.com/mooyoul/poo.email/issues/1#issuecomment-1381077954) as we're also considering using our own smtp server.

**Review by bezzang-dev — APPROVED** [review]
LGTM!

**Comment by bezzang-dev** [comment]
Thank you for the useful information!

As you say, I agree we use postgres on our machines only for local/test environment.

I'll refer to above comment when consider SMTP server.

**Pull request merged**
